### ISSUE TITLE
Can't connect to SauceLabs proxy

### ISSUE THREAD

**Issue by marvinhagemeister** [modernweb-dev/web#1114]
The last issue we're facing over at Preact is that we can't get the SauceLabs plugin to connect to SauceLabs. The `webdriver` fails when attempting to create a session. Double checked that our credentials are correct.

```bash
[Saucelabs] Setting up Sauce Connect proxy...
2020-12-23T00:56:31.935Z ERROR webdriver: Request failed with status 401 due to unknown error: failed serving request POST /wd/hub/session: Unauthorized
2020-12-23T00:56:31.936Z ERROR webdriver: unknown error: failed serving request POST /wd/hub/session: Unauthorized
    at Object.getErrorFromResponseBody (/home/runner/work/***/***/node_modules/webdriver/build/utils.js:94:12)
    at WebDriverRequest._request (/home/runner/work/***/***/node_modules/webdriver/build/request.js:134:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.startWebDriverSession (/home/runner/work/***/***/node_modules/webdriver/build/utils.js:29:20)
    at async Function.newSession (/home/runner/work/***/***/node_modules/webdriver/build/index.js:30:45)
    at async Object.exports.remote (/home/runner/work/***/***/node_modules/webdriverio/build/index.js:60:22)
    at async SauceLabsLauncher.initialize (/home/runner/work/***/***/node_modules/@web/test-runner-webdriver/dist/webdriverLauncher.js:21:27)
    at async TestRunner.start (/home/runner/work/***/***/node_modules/@web/test-runner/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:60:25)
    at async Object.startTestRunner (/home/runner/work/***/***/node_modules/@web/test-runner/dist/startTestRunner.js:49:9)
Error while running tests:
Error: Failed to create session.
failed serving request POST /wd/hub/session: Unauthorized
    at Object.startWebDriverSession (/home/runner/work/***/***/node_modules/webdriver/build/utils.js:34:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.newSession (/home/runner/work/***/***/node_modules/webdriver/build/index.js:30:45)
    at async Object.exports.remote (/home/runner/work/***/***/node_modules/webdriverio/build/index.js:60:22)
    at async SauceLabsLauncher.initialize (/home/runner/work/***/***/node_modules/@web/test-runner-webdriver/dist/webdriverLauncher.js:21:27)
    at async TestRunner.start (/home/runner/work/***/***/node_modules/@web/test-runner/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:60:25)
    at async Object.startTestRunner (/home/runner/work/***/***/node_modules/@web/test-runner/dist/startTestRunner.js:49:9)
```

Steps to reproduce:

1. Clone repo `git clone git@github.com:preactjs/preact.git`
2. Check out `wtr` branch: `git checkout wtr`
3. Run `npm i`
4. Run `npm run test:wtr` (expects env variables `SAUCE_USERNAME` and `SAUCE_USERNAME` to be set)

**Comment by LarsDenBakker** [comment]
Looks like we need to update the config. I made a PR with the changes: https://github.com/preactjs/preact/pull/2885

**Comment by marvinhagemeister** [comment]
Thank you so much again for looking into it! Works like a charm with these changes :raised_hands:
