### ISSUE TITLE
[test-runner-playwright] Error: page.goto: Navigation failed because page crashed!

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#1392]
## Description

After upgrading to Playwright 1.10.0 the following error started to happen in one of the test files we have:

```
packages/vaadin-crud/test/crud.test.js:

 ❌ Tests were interrupted because the browser disconnected.

 ❌ Error: page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "about:blank", waiting until "load"
============================================================
```

I have tried to set `concurrency: 1` and added the debug flag, here is the output:

<details>
<summary>Full log</summary>

```
$ yarn test:webkit --group vaadin-crud
yarn run v1.22.5
$ DEBUG=pw:api web-test-runner --config web-test-runner-webkit.config.js --group vaadin-crud
  pw:api => browserType.launch started +0ms

Webkit: |██████████                    | 0/3 test files | 0 passed, 0 failed

Running tests...

  pw:api <= browserType.launch succeeded +510ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +122ms
  pw:api => browserContext.newPage started +33ms
  pw:api <= browserContext.newPage succeeded +511ms
  pw:api => page.setViewportSize started +0ms
  pw:api <= page.setViewportSize succeeded +6ms
  pw:api => page.goto started +0ms
  pw:api navigating to "http://localhost:8000/?wtr-session-id=dcd377ac-ede8-4fc1-8c2f-cbd32f8fb00c", waiting until "load" +3ms
  pw:api   navigated to "http://localhost:8000/?wtr-session-id=dcd377ac-ede8-4fc1-8c2f-cbd32f8fb00c" +81ms
  pw:api   "load" event fired +246ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api <= page.goto succeeded +36ms
Webkit: |██████████                    | 1/3 test files | 16 passed, 0 failed

Running tests...

  pw:api => page.setViewportSize started +13ms
  pw:api <= page.setViewportSize succeeded +9ms
  pw:api => page.goto started +0ms
  pw:api navigating to "http://localhost:8000/?wtr-session-id=9ec4bd19-43ae-4bfc-ae73-0a85ea872ddf", waiting until "load" +10ms
  pw:api   navigated to "http://localhost:8000/?wtr-session-id=9ec4bd19-43ae-4bfc-ae73-0a85ea872ddf" +126ms
  pw:api   "domcontentloaded" event fired +5ms
  pw:api   "load" event fired +82ms
  pw:api <= page.goto succeeded +4ms
  pw:api   "networkidle" event fired +1s
Webkit: |████████████████████          | 2/3 test files | 43 passed, 0 failed

Running tests...

  pw:api => page.setViewportSize started +2ms
  pw:api <= page.setViewportSize succeeded +4ms
  pw:api => page.goto started +0ms
  pw:api navigating to "http://localhost:8000/?wtr-session-id=e074862f-fd73-4451-b565-6f98f2bc5086", waiting until "load" +0ms
  pw:api   navigated to "http://localhost:8000/?wtr-session-id=e074862f-fd73-4451-b565-6f98f2bc5086" +80ms
  pw:api   "domcontentloaded" event fired +101ms
  pw:api   "load" event fired +5ms
Webkit: |██████████████████████████████| 3/3 test files | 43 passed, 0 failed
packages/vaadin-crud/test/crud.test.js:

 ❌ Tests were interrupted because the browser disconnected.

 ❌ Error: page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "about:blank", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
    page.goto: Navigation failed because page crashed!
    =========================== logs ===========================
    navigating to "about:blank", waiting until "load"
    ============================================================
    Note: use DEBUG=pw:api environment variable to capture Playwright logs.
    Error
        at Object.captureStackTrace (/Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/utils/stackTrace.js:48:19)
        at Connection.sendMessageToServer (/Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/connection.js:69:48)
        at Proxy.<anonymous> (/Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/channelOwner.js:64:61)
        at /Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/frame.js:102:65
        at Frame._wrapApiCall (/Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/channelOwner.js:77:34)
        at Frame.goto (/Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/frame.js:100:21)
        at /Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/page.js:296:60
        at Page._attributeToPage (/Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/page.js:231:20)
        at Page.goto (/Users/sergey/vaadin/vaadin-web-components/node_modules/playwright/lib/client/page.js:296:21)
        at PlaywrightLauncherPage.stopSession (/Users/sergey/vaadin/vaadin-web-components/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncherPage.js:32:35)

Webkit: |██████████████████████████████| 3/3 test files | 43 passed, 0 failed

Error while running tests.

  pw:api <= browser.close succeeded +55ms
error Command failed with exit code 1.
```

</details>

## See also

https://github.com/vaadin/web-components/issues/219

**Comment by web-padawan** [comment]
I tried to downgrade Playwright to `1.9.2` and it helped: https://github.com/vaadin/web-components/commit/f6953a6bab15ec2c4f9b4403c9a7598e548819a4

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/microsoft/playwright/issues/6202 as this is not a bug of the test runner or a plugin.
