### ISSUE TITLE
[@web/test-runner] plugins_1.filePlugin is not a function

### ISSUE THREAD

**Issue by msteller-connyun** [modernweb-dev/web#1438]
In the version 0.13.2, 0.13.3, and 0.13.4 of `@web/test-runner` I’m getting the error 

```
TypeError: plugins_1.filePlugin is not a function
    at Object.parseConfig (...node_modules/@web/test-runner/dist/config/parseConfig.js:195:138)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.startTestRunner (...node_modules/@web/test-runner/dist/startTestRunner.js:26:42)
```

The missing plugin should be part of @web/test-runner-commands which is used in newest version (0.4.5), but it's missing there.

If I change @web/test-runner to version  0.13.1 the error no longer occurs.

**Comment by LarsDenBakker** [comment]
Sometimes versions in the package lock don't get updated properly, can you make sure you're on the latest in your lockfile? Either by updating them manually, or by regenerating the lockfile.

**Comment by web-padawan** [comment]
Closing per above comment.
