### ISSUE TITLE
Issues resolving Storybook imports when building for prod

### ISSUE THREAD

**Issue by sgammon** [modernweb-dev/web#1480]
Hey there modernweb-devs,

We're having issues building using the `@web/dev-server-storybook` package. It works in development just fine, but can't resolve relative imports at build time when we run `build-storybook`:

**`package.json`** (full dependencies available [here](https://gist.github.com/sgammon/b4115c2a22f053dca61e1791296568ce)):
```json
{
  "scripts": {
    "catalog": "wds --config tools/devserver.config.mjs",
    "storybook:build": "build-storybook --config-dir=storybook/.storybook --output-dir=storybook/dist",
  },
  "devDependencies": {
    "...": "lots of stuff here",
    "@web/dev-server": "^0.1.17",
    "@web/dev-server-esbuild": "^0.2.12",
    "@web/dev-server-storybook": "^0.3.5",
    "@web/storybook-prebuilt": "^0.1.20",
    "typescript": "3.9.7"
  }
}
```

**`storybook/.storybook/main.js`**:
```js
const css = require('rollup-plugin-import-css');

module.exports = {
  stories: ['../stories/**/*.stories.@(js|jsx|ts|tsx)'],
  rollupConfig(config) {
    // allow CSS imports
    config.plugins.push(css());
    return config;
  }
};
```

**`storybook/stories/Button.stories.ts`**:
```
import '../../elements/standard/button/button';

// Storybook code here
```

**`elements/standard/button/button.ts`**:
```
// valid button code here
```

`@web/dev-server` has no trouble finding this import when we run `wds` via the package scripts above. However, when we run `build-storybook`, also via the package scripts, it results in:

```
(node:20818) UnhandledPromiseRejectionWarning: Error: Could not resolve '../../elements/standard/button/button' from storybook/stories/Button.stories.ts
    at error (/Volumes/VANTAGE/lit-bazel/node_modules/@web/dev-server-storybook/node_modules/rollup/dist/shared/rollup.js:7426:30)
    at ModuleLoader.handleResolveId (/Volumes/VANTAGE/lit-bazel/node_modules/@web/dev-server-storybook/node_modules/rollup/dist/shared/rollup.js:19141:24)
    at /Volumes/VANTAGE/lit-bazel/node_modules/@web/dev-server-storybook/node_modules/rollup/dist/shared/rollup.js:19097:22
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/Volumes/VANTAGE/lit-bazel/node_modules/@web/dev-server-storybook/node_modules/rollup/dist/shared/rollup.js:19095:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/Volumes/VANTAGE/lit-bazel/node_modules/@web/dev-server-storybook/node_modules/rollup/dist/shared/rollup.js:19071:9)
    at async Promise.all (index 2)
    at async ModuleLoader.fetchStaticDependencies (/Volumes/VANTAGE/lit-bazel/node_modules/@web/dev-server-storybook/node_modules/rollup/dist/shared/rollup.js:19095:34)
    at async Promise.all (index 0)

```

**Comment by Marshal27** [comment]
Are you using any specific plugins in your `web-dev-server.config.mjs`? 

Might be helpful to show that config, running storybook locally in dev doesn't use the main.js config, I believe, and uses `web-dev-server.config.mjs`... only `build-storybook` will user `main.js`.

**Comment by Marshal27** [comment]
this was the fix for me in `main.js`.

```js
rollupConfig(config) {
    config.plugins.unshift(
      typescript(),
      nodeResolve(),
      commonjs({
        include: /node_modules/,
      }),
    );
```
