### ISSUE TITLE
[test-runner-junit-reporter] x.replace is not a function (sometimes)

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#1495]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@web/test-runner-junit-reporter@0.4.3` for the project I'm working on.

I'm not sure that this _fully_ addresses the issue at hand, but I have been running into the following error in CI:
```
TypeError: x.replace is not a function
    at stripXMLInvalidChars (/root/project/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js:61:43)
    at /root/project/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js:44:80
    at Array.map (<anonymous>)
    at /root/project/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js:44:55
    at Array.flatMap (<anonymous>)
    at escapeLogs (/root/project/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js:44:40)
    at Array.flatMap (<anonymous>)
    at /root/project/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js:179:52
    at Array.map (<anonymous>)
    at getTestRunXML (/root/project/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js:171:66)
```
As it's in CI I'm having trouble catching what exactly `x` is being set to here in order to understand why it doesn't have `x.replace`, but a hard check feels like it might be enough to prevent the issue from effecting people? I'll be looking more closely at this situation and will report back.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js b/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js
index a7e45a1..133feb8 100644
--- a/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js
+++ b/node_modules/@web/test-runner-junit-reporter/dist/junitReporter.js
@@ -58,7 +58,7 @@ const getTestDurationInSeconds = ({ duration }) => (typeof duration === 'undefin
 const INVALID_CHARACTERS_REGEX = 
 // eslint-disable-next-line no-control-regex
 /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007f-\u0084\u0086-\u009f\uD800-\uDFFF\uFDD0-\uFDFF\uFFFF\uC008]/g;
-const stripXMLInvalidChars = (x) => x.replace(INVALID_CHARACTERS_REGEX, '');
+const stripXMLInvalidChars = (x) => x && x.replace ? x.replace(INVALID_CHARACTERS_REGEX, '') : x;
 /**
  * Makes a `<failure>` element
  */
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Westbrook** [comment]
Fixed in https://github.com/modernweb-dev/web/pull/1504
