### ISSUE TITLE
[test-runner]: FAST-element + fixture does not upgrade the element

### ISSUE THREAD

**Issue by ParamagicDev** [modernweb-dev/web#1559]
Closing...not really sure its a priority, ill just write html tests.

**Comment by bennypowers** [comment]
do you have a reproduction?

**Comment by ParamagicDev** [comment]
@bennypowers I do have a reproduction.

The weird thing is Im not sure its an issue with the `fixture()` function. There seems to be something more dubious at play here.

Even weirder, named imports seem to be having a different effect than side-effect only imports and i have no idea why.

Heres the repo:

https://github.com/ParamagicDev/fast-element-typescript-starter/tree/bug-repro

branch is: "bug-repo"

Heres the file in question:

https://github.com/ParamagicDev/fast-element-typescript-starter/blob/bug-repro/test/my-counter.test.ts

in particular, theres something bizarre going on with imports:

```javascript
// If this gets changed to: import "../src/my-counter", everything works.
import { MyCounter } from '../src/my-counter'

describe('MyCounter', () => {
  it('increases the count on button click', async () => {
    // Uncomment below, "button" / shadowRoot will be defined.
    // console.log(MyCounter)
    const container = document.createElement('div')
    container.dataset.testId = 'test-container'
    container.innerHTML = '<my-counter></my-counter>'
    document.body.appendChild(container)

    const el = container.firstElementChild as MyCounter
    const button = el?.shadowRoot?.querySelector('button[title="increment"]') as HTMLButtonElement
    button.click()
  })
})
```

**Comment by bennypowers** [comment]
Looks like typescript is treating your import as `import type` since you don't use `MyCounter` as a value

Change the test to

```ts
import { MyCounter } from '../src/my-counter'
import { defineCE } from '@open-wc/testing'

describe('MyCounter', () => {
  it('increases the count on button click', async () => {
    const tag = defineCE(class extends MyCounter {});
    const el = await fixture(`<${tag}></${tag}>`);
    const button = el?.shadowRoot?.querySelector('button[title="increment"]') as HTMLButtonElement
    button.click()
  })
})
```

using `defineCE` in tests is good practice anyways

**Comment by ParamagicDev** [comment]
So the fix you suggested didnt quite work.

With this:

```js
const tag = defineCE(class extends MyCounter {})
const el = await fixture(`<${tag}`></${tag}`)
```

I got the following error:

<details>

<summary>
```bash
 ❌ MyCounter > increases the count on button click
      Error: Uncaught TypeError: Failed to construct 'HTMLElement': This instance is already constructed (http://localhost:8001/node_modules/@w
ebcomponents/scoped-custom-element-registry/scoped-custom-element-registry.min.js:20)
```
</summary>

```bash
➜  fast-element-typescript-starter git:(main) ✗ yarn test
yarn run v1.22.10
$ yarn fix && tsc -p tsconfig-dev.json && web-test-runner
$ ts-standard src/ test/ --fix

test/my-counter.test.ts:

 🚧 Browser logs on Chromium:
      TypeError: Failed to construct 'HTMLElement': This instance is already constructed
        at new window.HTMLElement (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:165:23)
        at new <anonymous> (node_modules/@microsoft/fast-element/dist/esm/components/fast-element.js:8:13)
        at new MyCounter (src/my-counter/index.ts:29:7)
        at new <anonymous> (test/my-counter.test.ts:8:25)
        at w (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:333:6)
        at new b (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:226:10)
        at HTMLDivElement.set [as innerHTML] (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:392:23)
        at stringFixtureSync (node_modules/@open-wc/testing-helpers/src/stringFixture.js:17:24)
        at stringFixture (node_modules/@open-wc/testing-helpers/src/stringFixture.js:36:14)
        at fixture (node_modules/@open-wc/testing-helpers/src/fixture-no-side-effect.js:58:12)
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      Error: done() called multiple times in test <MyCounter increases the count on button click>; in addition, done() received error: TypeError: Cannot read property 'click' of undefined
        at createMultipleDoneError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:242926)
        at node_modules/@web/test-runner-mocha/dist/autorun.js:1:257522
        at a (node_modules/@web/test-runner-mocha/dist/autorun.js:1:257532)
        at node_modules/@web/test-runner-mocha/dist/autorun.js:1:258588
 🚧 Browser logs on Webkit:
      TypeError: Cannot instantiate a custom element inside its own constructor during upgrades
        at node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:166:6
        at w (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:336:4)
        at b (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:226:20)
        at set (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:392:28)
        at stringFixtureSync (node_modules/@open-wc/testing-helpers/src/stringFixture.js:17:13)
        at node_modules/@open-wc/testing-helpers/src/stringFixture.js:36:31
        at test/my-counter.test.ts:9:40

 ❌ MyCounter > increases the count on button click
      Error: Uncaught TypeError: Failed to construct 'HTMLElement': This instance is already constructed (http://localhost:8001/node_modules/@webcomponents/scoped-custom-element-registry/scoped-custom-element-registry.min.js:20)
        at HTMLDivElement.set [as innerHTML] (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:392:23)
        at stringFixtureSync (node_modules/@open-wc/testing-helpers/src/stringFixture.js:17:24)
        at stringFixture (node_modules/@open-wc/testing-helpers/src/stringFixture.js:36:14)
        at fixture (node_modules/@open-wc/testing-helpers/src/fixture-no-side-effect.js:58:12)
        at o.<anonymous> (test/my-counter.test.ts:9:21)

Chromium: |██████████████████████████████| 1/1 test files | 0 passed, 1 failed
Webkit:   |██████████████████████████████| 1/1 test files | 0 passed, 1 failed

Finished running tests in 1.6s with 2 failed tests.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  fast-element-typescript-starter git:(main) ✗ yarn test
yarn run v1.22.10
$ yarn fix && tsc -p tsconfig-dev.json && web-test-runner
$ ts-standard src/ test/ --fix

test/my-counter.test.ts:

 ❌ MyCounter > increases the count on button click
      Error: Failed to execute 'define' on 'CustomElementRegistry': this constructor has already been used with this registry
      Failed to execute 'define' on 'CustomElementRegistry': this constructor has already been used with this registry

Chromium: |██████████████████████████████| 1/1 test files | 0 passed, 1 failed
      TypeError: Cannot instantiate a custom element inside its own constructor during upgrades                                        [41/509]
        at node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:166:6
        at node_modules/@microsoft/fast-element/dist/esm/components/fast-element.js:8:18
        at MyCounter (src/my-counter/index.ts:29:7)
        @
        at w (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:336:4)
        at b (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:226:20)
        at set (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:392:28)
        at stringFixtureSync (node_modules/@open-wc/testing-helpers/src/stringFixture.js:17:13)
        at node_modules/@open-wc/testing-helpers/src/stringFixture.js:36:31
        at test/my-counter.test.ts:9:40

 ❌ MyCounter > increases the count on button click
      Error: Uncaught TypeError: Failed to construct 'HTMLElement': This instance is already constructed (http://localhost:8001/node_modules/@w
ebcomponents/scoped-custom-element-registry/scoped-custom-element-registry.min.js:20)
        at HTMLDivElement.set [as innerHTML] (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.js:
392:23)
        at stringFixtureSync (node_modules/@open-wc/testing-helpers/src/stringFixture.js:17:24)
        at stringFixture (node_modules/@open-wc/testing-helpers/src/stringFixture.js:36:14)
        at fixture (node_modules/@open-wc/testing-helpers/src/fixture-no-side-effect.js:58:12)
        at o.<anonymous> (test/my-counter.test.ts:9:21)
```
</details>


So instead I did this:


```js
const tag = new MyCounter().tagName
const el = await fixture(`<${tag}></${tag}>`);
```

and it worked like a charm. Thanks for debugging this with me.
