### ISSUE TITLE
[dev-server-rollup] Failing test: node modules resolved outside root directory are rewritten with commonjs

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#1568]
There is one test failing after upgrading `@rollup/plugin-node-resolve` to 13.0.0 (#1433).

```sh
  1) @rollup/plugin-node-resolve
       node modules resolved outside root directory are rewritten with commonjs:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/web/web/packages/dev-server-rollup/test/node/plugins/node-resolve.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

See https://github.com/modernweb-dev/web/pull/1567/checks?check_run_id=3159207368

Downgrading back to `11.0.0` makes this test pass. The reason is most likely this PR: https://github.com/rollup/plugins/pull/799

**Comment by bennypowers** [comment]
@web-padawan what was the root cause? reverting the plugin version is breaking `esbuildPlugin({ ts: true })` for lit2

**Comment by web-padawan** [comment]
I will investigate.

**Comment by web-padawan** [comment]
Reopening as the test was not fixed but skipped in #1942
