### ISSUE TITLE
@web/test-server Failed to resolve module with dynamic import(/* webpackChunkName: "test" */ "test") 

### ISSUE THREAD

**Issue by amitdhiman000** [modernweb-dev/web#1684]
Failed to resolve dynamic import inside test cases, when we add comment inside dynamic import call.
e.g. `import(/* webpackChunkName: "test" "@xmldom/xmldom")` call.

```
TypeError: Failed to resolve module specifier '@xmldom/xmldom'
        at src/index.ts:4:26
        at Generator.next (<anonymous>)
        at dist/src/index.js:7:71
        at new Promise (<anonymous>)
        at __awaiter (dist/src/index.js:3:12)
        at findNodeValue (dist/src/index.js:11:12)
        at src/index.spec.ts:11:20
        at Generator.next (<anonymous>)
        at dist/src/index.spec.js:7:71
        at new Promise (<anonymous>)
```

**Comment by bennypowers** [comment]
Can you provide your config?

**Comment by amitdhiman000** [comment]
@benjamind 

sample  [repo link](https://github.com/amitdhiman000/xmldom_316)
