### ISSUE TITLE
WebKit stopped working

### ISSUE THREAD

**Issue by arv** [modernweb-dev/web#1797]
I'm trying to upgrade to the latest web test runner but WebKit is no longer working for me.

My test config is here: https://github.com/rocicorp/replicache/blob/main/web-test-runner.config.mjs

And here is the stacktrace:

```
 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/arv/src/replicache/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/arv/src/replicache/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:78:43)
        at PlaywrightLauncher.startSession (/Users/arv/src/replicache/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:45:31)
```

And package.json:

```
    "@web/dev-server": "0.1.28",
    "@web/dev-server-esbuild": "^0.2.16",
    "@web/test-runner": "^0.13.22",
    "@web/test-runner-playwright": "^0.8.8",
    "playwright": "^1.16.3",
```

**Comment by arv** [comment]
Seems to work again with

```
    "@web/dev-server": "0.1.29",
    "@web/dev-server-esbuild": "^0.2.16",
    "@web/test-runner": "^0.13.25",
    "@web/test-runner-playwright": "^0.8.8",
    "playwright": "^1.17.2",
```
