### ISSUE TITLE
[web-test-runner] Error related to coverage in 0.15.2

### ISSUE THREAD

**Issue by driesva** [modernweb-dev/web#2186]
With `coverage: true` in web test runner config, we get following error since version 0.15.2

```
 ❌ TypeError: this.puppeteerPage._client.send is not a function 
    TypeError: this.puppeteerPage._client.send is not a function
        at ChromeLauncherPage.collectTestCoverage (/foobar/node_modules/@web/test-runner-chrome/dist/ChromeLauncherPage.js:61:60)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async ChromeLauncherPage.stopSession (/foobar/node_modules/@web/test-runner-chrome/dist/ChromeLauncherPage.js:28:30)
        at async ChromeLauncher.stopSession (/foobar/node_modules/@web/test-runner-chrome/dist/ChromeLauncher.js:142:24)
```

Coverage report is also empty.

With version 0.15.1 everything works OK.

**Comment by RobBosman** [comment]
See also https://github.com/puppeteer/puppeteer/issues/8533#issuecomment-1159489230.
