### ISSUE TITLE
Module not found 'data:text' - Webpack

### ISSUE THREAD

**Issue by 1bberto** [modernweb-dev/web#2220]
Im trying to run the tests on my application and I'm currently facing this issue

```javascript
node: v16.20.0
npm: 8.19.4
webpack 5.78.0
```

```javascript
[
  {
    moduleIdentifier: 'javascript/esm|C:\\projects\\node_modules\\@web\\test-runner-commands\\browser\\commands.mjs',
    moduleName: './node_modules/@web/test-runner-commands/browser/commands.mjs',
    loc: '160:23-78',
    message: "Module not found: Error: Can't resolve 'data:text' in 'C:\\projects\\node_modules\\@web\\test-runner-commands\\browser'",
    moduleId: './node_modules/@web/test-runner-commands/browser/commands.mjs',
    moduleTrace: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    details: '',
    stack: "ModuleNotFoundError: Module not found: Error: Can't resolve 'data:text' in 'C:\\projects\\node_modules\\@web\\test-runner-commands\\browser'\n" +
      '    at C:\\projects\\node_modules\\webpack\\lib\\Compilation.js:2016:28\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\ContextModuleFactory.js:214:15\n' +
      '    at C:\\projects\\node_modules\\neo-async\\async.js:2830:7\n' +
      '    at C:\\projects\\node_modules\\neo-async\\async.js:6877:13\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\ContextModuleFactory.js:184:26\n' +
      '    at finishWithoutResolve (C:\\projects\\node_modules\\enhanced-resolve\\lib\\Resolver.js:312:11)\n' +
      '    at C:\\projects\\node_modules\\enhanced-resolve\\lib\\Resolver.js:386:15\n' +
      '    at C:\\projects\\node_modules\\enhanced-resolve\\lib\\Resolver.js:435:5\n' +
      '    at eval (eval at create (C:\\projects\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:27:1)\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\cache\\ResolverCachePlugin.js:257:15\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\cache\\ResolverCachePlugin.js:177:36\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\HookWebpackError.js:68:3\n' +
      '    at Hook.eval [as callAsync] (eval at create (C:\\projects\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:15:1)\n' +
      '    at Cache.store (C:\\projects\\node_modules\\webpack\\lib\\Cache.js:107:20)\n' +
      '    at ItemCacheFacade.store (C:\\projects\\node_modules\\webpack\\lib\\CacheFacade.js:137:15)\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\cache\\ResolverCachePlugin.js:173:18\n' +
      '    at jobDone (C:\\projects\\node_modules\\webpack\\lib\\FileSystemInfo.js:1995:5)\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\FileSystemInfo.js:2311:7\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:352:5\n' +
      '    at Hook.eval [as callAsync] (eval at create (C:\\projects\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at AsyncQueue._handleResult (C:\\projects\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:322:21)\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:305:11\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\FileSystemInfo.js:3508:12\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:352:5\n' +
      '    at Hook.eval [as callAsync] (eval at create (C:\\projects\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at AsyncQueue._handleResult (C:\\projects\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:322:21)\n' +
      '    at C:\\projects\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:305:11\n' +
      '    at Array.<anonymous> (C:\\projects\\node_modules\\webpack\\lib\\FileSystemInfo.js:3495:4)\n' +
      '    at runCallbacks (C:\\projects\\node_modules\\enhanced-resolve\\lib\\CachedInputFileSystem.js:27:15)\n' +
      '    at C:\\projects\\node_modules\\enhanced-resolve\\lib\\CachedInputFileSystem.js:200:4\n' +
      '    at C:\\projects\\node_modules\\graceful-fs\\graceful-fs.js:228:16\n' +
      '    at FSReqCallback.oncomplete (node:fs:192:23)'
  }
]
```

any ideas on how can I solve this problem?

**Comment by thepassle** [comment]
Why are you bundling `@web/test-runner-commands` with webpack?
