### ISSUE TITLE
[web-test-runner] "browser was unable to create and start a test page" in Windows, fine in Linux and macOS

### ISSUE THREAD

**Issue by trusktr** [modernweb-dev/web#2287]
I have some tests working great in Linux and macOS. When I try to run tests in Windows, it fails like this:

```
Error: Failed to create target for page (id = B7833EB8392EF96856BE762F201544BA)
 ❌ The browser was unable to create and start a test page after 30000ms. You can increase this timeout with the browserStartTimeout option. 
    at CDPBrowser._createPageInContext (D:\a\bytescript\bytescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Browser.js:283:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChromeLauncher.createNewPage (D:\a\bytescript\bytescript\node_modules\@web\test-runner-chrome\dist\ChromeLauncher.js:132:215)
    at async ChromeLauncher.startSession (D:\a\bytescript\bytescript\node_modules\@web\test-runner-chrome\dist\ChromeLauncher.js:[91](https://github.com/bytescript/bytescript/actions/runs/5097548282/jobs/9164140820?pr=27#step:4:92):20)
Error while running tests.
```

This is in a GitHub Action:

https://github.com/bytescript/bytescript/actions/runs/5097548282/jobs/9164140820?pr=27

Any ideas why the browser times out when running web test runner in Windows?

**Comment by thepassle** [comment]
It seems like this error is coming from Puppeteer itself, it's probably more effective to open an issue there, or try to see if any similar errors have been reported on Puppeteer

**Comment by trusktr** [comment]
Switching to the [playwright launcher](https://modern-web.dev/docs/test-runner/browser-launchers/playwright/) solved the issue. No more puppeteer.
