### ISSUE TITLE
Mocha timeout errors don't tell me which test is timing out.

### ISSUE THREAD

**Issue by koddsson** [modernweb-dev/web#2306]
I'm not sure why but sometimes when tests fail in my test suite due to timeouts I don't get a stacktrace that points me to the correct test so that I can work on it.

 ~/src/my-app/ [feature/new-mocks*] npm test

> my-app@2.1.2 test
> wtr

test/my-app-stories.test.js:

 ❌ Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at createTimeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:191495)
      at ds._timeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:195728)
      at node_modules/@web/test-runner-mocha/dist/autorun.js:1:193809

Chrome: |██████████████████████████████| 3/3 test files | 14 passed, 3 failed, 8 skipped

Finished running tests in 5.9s with 3 failed tests.
```

See in the stacktrace (which is minified, not sure why that is either 🤔 ) that it doesn't point to the actual test that is timing out.

**Comment by fskpf** [comment]
Maybe this is related: I had a similar mysterious exception after upgrading test-runner from `0.13.27` to the current `0.16.1` version. In my case, I narrowed it down to running multiple test files in parallel (it worked perfectly fine with the older version of the test-runner).

To fix it, I could either change the `files` to just a single file or set `concurrency: 1` in the [test-runner config](https://modern-web.dev/docs/test-runner/cli-and-configuration/).
