### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by robertsLando** [modernweb-dev/web#2538]
I would like to be able to run tests in an HTTPS environment but I cannot find options to do this.

Related issue: https://github.com/modernweb-dev/web/issues/2517

**Comment by bashmish** [comment]
I found that we do support HTTPS by using `http2` flag.

Can you try adding `http2: true` to your config, and `sslKey` and `sslCert` if needed.

```
export interface TestRunnerCoreConfig {
  // ...
  http2?: boolean;
  sslKey?: string;
  sslCert?: string;
  // ...
}
```

This is documented only in WDS though:
https://modern-web.dev/docs/dev-server/cli-and-configuration/

And not in WTR:
https://modern-web.dev/docs/test-runner/cli-and-configuration/

**Comment by robertsLando** [comment]
Ok I confirm this is working, I only report that the addresses printed on console are still using `http` and if you set the `open` to `true` it opens the `http` url resulting to a 404. If I manually fix http --> https it works BTW. I think may be worth adding this to docs too

**Comment by robertsLando** [comment]
Ok I think part of #2540 is also related to this, when http2 is enabled and playwright browsers are lunched the url is wrong there too:

```
test/browser/test.js:

 ❌ page.goto: net::ERR_EMPTY_RESPONSE at http://localhost:8001/?wtr-session-id=uqh67wN1nTY5Ieug0bLwQ
=========================== logs ===========================
navigating to "http://localhost:8001/?wtr-session-id=uqh67wN1nTY5Ieug0bLwQ", waiting until "load"
============================================================  (failed on Chromium)
    page.goto: net::ERR_EMPTY_RESPONSE at http://localhost:8001/?wtr-session-id=uqh67wN1nTY5Ieug0bLwQ
    =========================== logs ===========================
    navigating to "http://localhost:8001/?wtr-session-id=uqh67wN1nTY5Ieug0bLwQ", waiting until "load"
    ============================================================
        at PlaywrightLauncherPage.runSession (/home/daniel/GitProjects/MQTT.js/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncherPage.js:26:35)
        at async PlaywrightLauncher.startSession (/home/daniel/GitProjects/MQTT.js/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:45:9)
```

If I disalble http2 error goes away but I think then the problem is due to the mixed content...

**Comment by bashmish** [comment]
Can you please make a smallest possible reproduction of this issue?

**Comment by robertsLando** [comment]
Just checkout this: https://github.com/mqttjs/MQTT.js/pull/1722

**Comment by bashmish** [comment]
By `smallest possible reproduction` I mean smth that contains minimum code that is required to show the error, e.g. minimal config and 1 test file with 1 test, not the whole project.

**Comment by bashmish** [comment]
Btw, auto-open which doesn't respect `http2` flag should definitely be fixed. I'm wondering more about the other error you are running into.

**Comment by robertsLando** [comment]
I will create a small repo to reproduce this, in the meanwhile if you want you can try doing what i described in my [comment](https://github.com/modernweb-dev/web/issues/2538#issuecomment-1795333616) (would save me effort in creating a repro of the issue).

I think the issue is not only related to the open, in general seems like `http2` flah is completely ignored code wise when building the url, so you see the url wrong everywhere: in console, open, playwright goTo page and so on....

**Comment by robertsLando** [comment]
Here is the smallest possible repro: https://github.com/robertsLando/wtr-bug-test

**Comment by bashmish** [comment]
Makes sense indeed, thanks for your time analysing this and providing this repro. I saw code that is handling the flag `http2` for the URL construction, so I assumed it was working fine, but apparently not in all contexts and not for all features. So looks like is needd more work for WTR.

**Comment by robertsLando** [comment]
Ok so seems the missing piece was this setting:

```js
protocol: 'https:',
```

When this is set everything else is ok. Not sure if this is expected

**Comment by bashmish** [comment]
@robertsLando is `http2` still needed then?

I feel like some docs is missing to explain all this. Would be good to work on this improvement, so I'll keep this issue open.

**Comment by robertsLando** [comment]
> still needed then

Yeah seems without that something else is broken, I see on some places it uses `http2` to build the url and others use `protocol`

**Comment by klasjersevi** [comment]
I'm missing some of the built-in certificate options, specifically `.pfx` and `.passphrase` as I'm using pfx certificate instead of pem.

It would be nice if you could expose these as well.

More details: 
https://nodejs.org/docs/v8.6.0/api/http2.html#http2_http2_createsecureserver_options_onrequesthandler
https://nodejs.org/docs/v8.6.0/api/tls.html#tls_tls_createsecurecontext_options
