### ISSUE TITLE
[test-runner-cli] improve feedback details in failed test messages

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/web#258]
If we compare the feedback you get from jest vs test-runner/mocha I think there are improvements we can make

### Jest

```
 FAIL  ./sum.test.js
  ✕ adds 1 + 2 to equal 3 (19 ms)

  ● adds 1 + 2 to equal 3

    expect(received).toBe(expected) // Object.is equality

    Expected: 3
    Received: "10,000"

      2 |
      3 | test("adds 1 + 2 to equal 3", () => {
    > 4 |   expect(sum(1, 2)).toBe(3);
        |                     ^
      5 | });
      6 |
```

### Test Runner

```
test/sum.test.js:

 ❌ adds 1 + 2 to equal 3
      AssertionError: expected '10,000' to equal 3
        at n.<anonymous> (test/sum.test.js:5:24)
```

## Suggestion for Test Runner

```
test/sum.test.js:

 ❌ adds 1 + 2 to equal 3
     
    Expected: 3
    Received: "10,000"
    
      2 |
      3 | it('adds 1 + 2 to equal 3', () => {
    > 4 |   expect(sum(1, 2)).to.equal(3);
        |                     ^
      5 | });
      6 |

      AssertionError: expected '10,000' to equal 3
        at n.<anonymous> (test/sum.test.js:5:24)
```

**Comment by LarsDenBakker** [comment]
The error message itself comes from the assertion library, we can see if jest's assertion library has better error message: https://www.npmjs.com/package/expect

The code frame we can add, but it would clutter the terminal when there are multiple errors. I was wondering about the use case for it when you can also click to go to the file. Maybe we can add it when there are only one or two errors.

**Comment by daKmoR** [comment]
I often have tests with multiple expects in them... and often based on the assert you can't know what is causing the failed tests

```js
it('doSomething does not effect state', () => {
  const el = await fixture('...');

  expect(el.state).to.be.true;
  el.doSomething();
  expect(el.state).to.be.true;
});
```

now If I get the following assert error
```
AssertionError: expected false to equal true
  at n.<anonymous> (test/sum.test.js:5:24)
```

I do not know which one is failing the first or the second one.

Right now what I do is I comment out all expects except one and rerun the test and then line by line I uncomment until I find the one that is actually failing... most of the time you have a guess and you find it with one or two runs... still quite cumbersome.

Imho if it's more then 10 failing tests then whatever you display it will always be clutter the terminal... and if you only have 2-3 then this extra detail would add to solve the failing test...

We could think about adding that info only in focus mode? 🤔



Oh it seems I keep forgetting that I can click on this path next to anonymous... does that work in all editors? hmmm maybe we can make that more prominent?

```
 ❌ adds 1 + 2 to equal 3
      AssertionError: expected '10,000' to equal 3
      Open Failing Assert via test/sum.test.js:5:24
```

hmmm even then I think I would like to get a little more details in the console... even if it's just to determine if it's worth opening my editor 😅

**Comment by LarsDenBakker** [comment]
For errors with a rich diff, such as string diffs, we show an "at" entry which is just the first file in the stack trace. We could log that in these cases too, it would make it easier to spot. 

 The code frame we can still do for small amounts of errors indeed.

**Comment by LarsDenBakker** [comment]
I added the "at" for all test errors. The code frame will be a bit more complex to add, and we will need to think a bit more about when to show it and when not to show it.
