### ISSUE TITLE
browserContext.newPage: Target closed (failed on Webkit) on macOS with M1 

### ISSUE THREAD

**Issue by erbilnas** [modernweb-dev/web#2589]
Description
--------------

Hello everyone, Erbil here. I hope you're doing great!

I'm actively engaged in our project called [Baklava](https://github.com/Trendyol/baklava), a design system developed with Lit. Currently, we're utilizing your Playwright library to conduct component tests in our project. However, I've encountered a recurring error every time I attempt to run it on my local machine. We've picked up a small clue within our team. Another teammate of mine, using macOS 13, didn't encounter this error. Perhaps this information can assist you in diagnosing the issue. I'll provide the specifications below.

Enviroment
------------
- Machine: MacBook Pro M1 Max 32GB macOS Sonoma 14.2 (23C64)

- VS Code
```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0
```

- Package
```
    "@web/dev-server-esbuild": "0.2.16",
    "@web/dev-server-import-maps": "^0.0.7",
    "@web/dev-server-rollup": "^0.3.17",
    "@web/test-runner": "^0.15.2",
    "@web/test-runner-playwright": "^0.9.0",
    "@web/test-runner-puppeteer": "^0.12.0",
```

Error
-----------

```
> @trendyol/baklava@0.0.0-dev test
> web-test-runner --coverage
```

```
src/utilities/event.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/utilities/asset-paths.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/utilities/form-control.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/alert/bl-alert.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/utilities/string-boolean.converter.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/badge/bl-badge.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/button/bl-button.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/checkbox-group/bl-checkbox-group.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/dialog/bl-dialog.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/drawer/bl-drawer.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/dropdown/bl-dropdown.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/icon/bl-icon.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/input/bl-input.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/notification/bl-notification.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/pagination/bl-pagination.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/popover/bl-popover.test.ts:

 🚧 Browser logs on Chromium:
      BlPopover target only accepts an Element instance or a string id of a DOM element.
 🚧 Browser logs on Firefox:
      BlPopover target only accepts an Element instance or a string id of a DOM element.

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/progress-indicator/bl-progress-indicator.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/radio-group/bl-radio-group.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/select/bl-select.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/switch/bl-switch.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/tab-group/bl-tab-group.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/textarea/bl-textarea.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/tooltip/bl-tooltip.test.ts:

 🚧 Browser logs on Chromium:
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
 🚧 Browser logs on Firefox:
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.
      BlPopover target only accepts an Element instance or a string id of a DOM element.

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/checkbox-group/checkbox/bl-checkbox.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/dropdown/group/bl-dropdown-group.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/dropdown/item/bl-dropdown-item.test.ts:

 🚧 Browser logs on Chromium:
      bl-dropdown-item is designed to be used inside a bl-dropdown-group or bl-dropdown BlDropdownItem: <bl-dropdown-item></bl-dropdown-item>
      bl-dropdown-item is designed to be used inside a bl-dropdown-group or bl-dropdown BlDropdownItem: <bl-dropdown-item icon="info"></bl-dropdown-item>
      bl-dropdown-item is designed to be used inside a bl-dropdown-group or bl-dropdown BlDropdownItem: <bl-dropdown-item>dropdown-item</bl-dropdown-item>
 🚧 Browser logs on Firefox:
      bl-dropdown-item is designed to be used inside a bl-dropdown-group or bl-dropdown BlDropdownItem: <bl-dropdown-item></bl-dropdown-item>
      bl-dropdown-item is designed to be used inside a bl-dropdown-group or bl-dropdown BlDropdownItem: <bl-dropdown-item icon="info"></bl-dropdown-item>
      bl-dropdown-item is designed to be used inside a bl-dropdown-group or bl-dropdown BlDropdownItem: <bl-dropdown-item>dropdown-item</bl-dropdown-item>

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/notification/card/bl-notification-card.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/radio-group/radio/bl-radio.test.ts:

 🚧 Browser logs on Chromium:
      bl-radio is designed to be used inside a bl-radio-group BlRadio: <bl-radio value="cc">Credit Card</bl-radio>
 🚧 Browser logs on Firefox:
      bl-radio is designed to be used inside a bl-radio-group BlRadio: <bl-radio value="cc">Credit Card</bl-radio>

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/select/option/bl-select-option.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/tab-group/tab/bl-tab.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)

src/components/tab-group/tab-panel/bl-tab-panel.test.ts:

 ❌ browserContext.newPage: Target closed  (failed on Webkit)
    browserContext.newPage: Target closed
        at PlaywrightLauncher.createPage [as createPageFn] (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/index.js:31:155)
        at PlaywrightLauncher.createNewPage (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:68:43)
        at async PlaywrightLauncher.startSession (/Users/erbilnas/Documents/Projects/baklava/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:22)
```

```
Chromium: |██████████████████████████████| 31/31 test files | 351 passed, 0 failed, 9 skipped
Firefox:  |██████████████████████████████| 31/31 test files | 351 passed, 0 failed, 9 skipped
Webkit:   |██████████████████████████████| 31/31 test files | 0 passed, 0 failed

Code coverage: 100 %
View full coverage report at coverage/lcov-report/index.html

Error while running tests.
```

**Comment by erbilnas** [comment]
Does anyone have a comment regarding this matter?
