### ISSUE TITLE
[@web/test-runner-playwright] browserType.launch: Executable doesn't exist

### ISSUE THREAD

**Issue by dominikfryc** [modernweb-dev/web#2613]
Suddenly, my test workflow stopped working. I guess Playwright browsers got updated, and they're not compatible anymore.

I got this error:
```
❌ browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-1091/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     pnpm exec playwright install                                        ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝ 
at /home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-playwright@0.11.0/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:94:74
        at PlaywrightLauncher.getOrStartBrowser (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-playwright@0.11.0/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:96:15)
        at PlaywrightLauncher.startSession (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-playwright@0.11.0/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:41:36)
        at TestScheduler.startSession (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-core@0.13.0/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:103:67)
        at TestScheduler.runNextScheduled (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-core@0.13.0/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:83:30)
        at TestScheduler.schedule (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-core@0.13.0/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:47:14)
        at TestRunner.runTests (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-core@0.13.0/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:92:28)
        at TestRunner.start (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner-core@0.13.0/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:65:22)
        at async startTestRunner (/home/runner/work/test/test/node_modules/.pnpm/@web+test-runner@0.18.0_typescript@5.3.2/node_modules/@web/test-runner/dist/startTestRunner.js:[46]
```

Running the suggested command doesn't fix it. In my test workflow, I install Playwright with deps:
```
pnpm dlx playwright install --with-deps
```

When I used that command on localhost, it broke there, too.

**Comment by dominikfryc** [comment]
`pnpm update` solved the problem. Transitive dependency `playwright` got updated to the correct version.

**Comment by SRachamim** [comment]
How can I prevent this from happening? Tests should be deterministic given the same `yarn.lock`.

**Comment by SRachamim** [comment]
Any response the the above question?

How can I make sure my CI is always up-to-date with the correct Playwright version?
