### ISSUE TITLE
[dev-server-rollup] TypeError: Cannot destructure property 'skipSelf' of 'options' as it is undefined.

### ISSUE THREAD

**Issue by eight04** [modernweb-dev/web#2640]
```
Error while handling server request.
TypeError: Cannot destructure property 'skipSelf' of 'options' as it is undefined.
    at Object.resolve (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\@web\dev-server-rollup\dist\createRollupPluginContextAdapter.js:66:21)
    at Object.importStyle (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\rollup-plugin-cjs-es\index.js:174:35)
    at context.isImportPreferDefault (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\cjs-es\lib\context.js:17:38)
    at writeImport (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\cjs-es\lib\import-writer.js:33:15)
    at Array.map (<anonymous>)
    at Object.write (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\cjs-es\lib\import-writer.js:26:50)
    at Object.write (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\cjs-es\lib\writer.js:18:35)
    at transform (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\cjs-es\index.js:28:31)
    at async Object.transform (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\rollup-plugin-cjs-es\index.js:169:20)
    at async Object.transform (C:\Users\eight04\dev\linkify-plus-plus-core\node_modules\@web\dev-server-rollup\dist\rollupAdapter.js:293:34)
```

Thrown by this line
https://github.com/modernweb-dev/web/blob/f7fcf29cb79e82ad5622665d76da3f6b23d0ef43/packages/dev-server-rollup/src/createRollupPluginContextAdapter.ts#L81

I guess the signature of `resolve` is wrong? According to https://rollupjs.org/plugin-development/#this-resolve, it should probably be
```diff
-    async resolve(source: string, importer: string, options: ResolveOptions) {
+    async resolve(source: string, importer?: string, options?: ResolveOptions) {
```

The caller: https://github.com/eight04/rollup-plugin-cjs-es/blob/7243715be4166b908fb2aa71f664475b5cbbd90e/index.js#L174

**Comment by jarrodek** [comment]
I just got into the same issue. I created a dirty hack for now to correct the file manually during NPM's prepare hook, but it would be nice to have it fixed.
