### ISSUE TITLE
[test-runner] "Error: Expected a BufferedLogger instance."

### ISSUE THREAD

**Issue by bennypowers** [modernweb-dev/web#442]
I've been getting these:

```

Error: Expected a BufferedLogger instance.
    at Object.reportTestFileResults (/home/vsts/work/1/s/node_modules/@web/test-runner-cli/dist/reporter/defaultReporter.js:38:23)
    at TestRunnerCli.getTestResultReports (/home/vsts/work/1/s/node_modules/@web/test-runner/node_modules/@web/test-runner-cli/dist/cli/TestRunnerCli.js:229:118)
    at TestRunnerCli.reportTestResult (/home/vsts/work/1/s/node_modules/@web/test-runner/node_modules/@web/test-runner-cli/dist/cli/TestRunnerCli.js:212:38)
    at EventEmitter.<anonymous> (/home/vsts/work/1/s/node_modules/@web/test-runner/node_modules/@web/test-runner-cli/dist/cli/TestRunnerCli.js:128:22)
    at EventEmitter.emit (events.js:327:22)
    at TestSessionManager.emit (/home/vsts/work/1/s/node_modules/@web/test-runner-core/dist/utils/EventEmitter.js:16:24)
    at TestSessionManager.updateStatus (/home/vsts/work/1/s/node_modules/@web/test-runner-core/dist/test-session/TestSessionManager.js:33:14)
    at TestScheduler.stopSession (/home/vsts/work/1/s/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:116:27)
    at async EventEmitter.<anonymous> (/home/vsts/work/1/s/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:18:17)
```

This isn't causing test failures (exclusing false positives, which I haven't checked for)

`wtr --coverage` is exiting with 0 exit code

<details>
<summary>Here's the config:</summary>

```js
import dotenv from 'dotenv';
dotenv.config();

import { defaultReporter } from '@web/test-runner-cli';
import { junitReporter } from '@web/test-runner-junit-reporter';

import { fromRollup } from '@web/dev-server-rollup';
import rollupCommonjs from '@rollup/plugin-commonjs';
import replace from '@rollup/plugin-replace';

import litcss from 'es-dev-server-import-css';
import json from 'es-dev-server-import-json';
import graphql from 'es-dev-server-import-graphql';

const REPLACEMENTS = {
  // ...
};

const excludeCSS = [
  '/src/styles.css',
  // ...
];

export default {
  nodeResolve: true,
  coverage: true,
  files: [
    'src/**/*.test.js',
    'lib/**/*.test.js',
  ],
  plugins: [
    fromRollup(rollupCommonjs),
    fromRollup(replace, REPLACEMENTS),
    litcss({ exclude: excludeCSS }),
    json({ exclude: ['/custom-elements.json', '/licenses.json'] }),
    graphql(),
  ],
  reporters: [
    defaultReporter(),
    junitReporter({ outputPath: './results/test-results.xml' }),
  ],
  coverageConfig: {
    report: true,
    reportDir: 'coverage',
    threshold: {
      statements: 70,
      branches: 70,
      functions: 70,
      lines: 70,
    },
  },
};
```
</details>

<details>
<summary>devDependencies</summary>

```json
{
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@babel/plugin-proposal-export-namespace-from": "^7.10.4",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.10.4",
    "@babel/plugin-proposal-optional-chaining": "^7.11.0",
    "@graphql-codegen/cli": "^1.17.8",
    "@graphql-codegen/introspection": "^1.17.8",
    "@graphql-codegen/typescript": "^1.17.9",
    "@graphql-codegen/typescript-graphql-files-modules": "^1.17.8",
    "@graphql-codegen/typescript-operations": "^1.17.8",
    "@graphql-codegen/typescript-resolvers": "^1.17.9",
    "@graphql-tools/load-files": "^6.0.18",
    "@graphql-tools/merge": "^6.0.18",
    "@homebound/graphql-id-linter": "^1.5.0",
    "@kocal/rollup-plugin-graphql": "^1.0.0",
    "@open-wc/demoing-storybook": "^2.3.19",
    "@open-wc/rollup-plugin-html": "^1.2.2",
    "@open-wc/testing": "^2.5.24",
    "@pwrs/eslint-config": "0.0.8",
    "@rollup/plugin-alias": "^3.1.1",
    "@rollup/plugin-commonjs": "^15.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^9.0.0",
    "@rollup/plugin-replace": "^2.3.3",
    "@types/d3": "^5.7.2",
    "@types/lodash.debounce": "^4.0.6",
    "@types/luxon": "^1.24.3",
    "@types/ramda": "^0.27.14",
    "@web/test-runner": "^0.7.8",
    "@web/test-runner-puppeteer": "^0.6.2",
    "@web/test-runner-junit-reporter": "^0.1.1",
    "@web/test-runner-playwright": "^0.5.3",
    "@zerollup/ts-transform-paths": "^1.7.18",
    "apollo-storybook-core": "^0.5.4",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.1.0",
    "chai": "^4.2.0",
    "chokidar": "^3.4.2",
    "copyfiles": "^2.3.0",
    "dedent-tag": "^1.0.1",
    "deepmerge": "^4.2.2",
    "es-dev-server-import-css": "^2.1.0",
    "es-dev-server-import-graphql": "^2.1.0",
    "es-dev-server-import-json": "^2.1.0",
    "eslint": "^7.7.0",
    "esm": "^3.2.25",
    "find-config": "^1.0.0",
    "husky": "^4.2.5",
    "koa-proxies": "^0.11.0",
    "koa-router": "^9.4.0",
    "nodemon": "^2.0.4",
    "npm-check": "^5.9.2",
    "npm-run-all": "^4.1.5",
    "patch-package": "^6.2.2",
    "postcss-clean": "^1.1.0",
    "rollup": "^2.26.5",
    "rollup-plugin-analyzer": "^3.3.0",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-browsersync": "^1.1.0",
    "rollup-plugin-cleaner": "^1.0.0",
    "rollup-plugin-copy": "^3.3.0",
    "rollup-plugin-glob-import": "^0.4.5",
    "rollup-plugin-istanbul": "^2.0.1",
    "rollup-plugin-license": "^2.2.0",
    "rollup-plugin-lit-css": "^2.0.4",
    "rollup-plugin-minify-html-literals": "^1.2.5",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-globals": "^1.4.0",
    "rollup-plugin-sourcemaps": "^0.6.2",
    "rollup-plugin-styles": "^3.10.0",
    "rollup-plugin-terser": "^7.0.0",
    "rollup-plugin-visualizer": "^4.1.0",
    "rollup-plugin-watch-assets": "^1.0.1",
    "rollup-plugin-workbox": "^5.2.1",
    "stylelint": "^13.6.1",
    "stylelint-config-standard": "^20.0.0",
    "ts-lit-plugin": "^1.2.1",
    "ttypescript": "^1.5.11",
    "typescript": "^4.0.2",
    "web-component-analyzer": "^1.1.6"
  }
```

</details>

**Comment by LarsDenBakker** [comment]
This is strange, looking at the code I don't see any code path when this could happen. Do you get it all the time?

**Comment by LarsDenBakker** [comment]
Oh, this could happen if you have multiple instances of the CLI since we do an `instanceof` check.
