### ISSUE TITLE
500 error when .br file is present

### ISSUE THREAD

**Issue by arv** [modernweb-dev/web#565]
If there is an import looking like this:

```js
import * as m from './x.js';
```

and there is a `./x.js.br` file we get a cryptic stack trace:

```
▶ npx web-test-runner test.js


  TypeError: A.charCodeAt is not a function
      at /Users/arv/src/web-test-runner-br/node_modules/es-module-lexer/dist/lexer.cjs:1:296
      at Object.parse (/Users/arv/src/web-test-runner-br/node_modules/es-module-lexer/dist/lexer.cjs:1:312)
      at transformImports (/Users/arv/src/web-test-runner-br/node_modules/@web/dev-server-core/dist/plugins/transformModuleImportsPlugin.js:70:45)
      at transformModuleImportsWithPlugins (/Users/arv/src/web-test-runner-br/node_modules/@web/dev-server-core/dist/plugins/transformModuleImportsPlugin.js:149:12)
      at Object.transform (/Users/arv/src/web-test-runner-br/node_modules/@web/dev-server-core/dist/plugins/transformModuleImportsPlugin.js:161:55)
      at /Users/arv/src/web-test-runner-br/node_modules/@web/dev-server-core/dist/middleware/pluginTransformMiddleware.js:44:103
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async /Users/arv/src/web-test-runner-br/node_modules/@web/dev-server-core/dist/middleware/etagCacheMiddleware.js:9:9
      at async /Users/arv/src/web-test-runner-br/node_modules/@web/dev-server-core/dist/middleware/watchServedFilesMiddleware.js:15:9
      at async /Users/arv/src/web-test-runner-br/node_modules/@web/test-runner-core/dist/server/middleware/cacheMiddleware.js:10:9

test.js:

 🚧 Browser logs:
      Failed to load resource: the server responded with a status of 500 (Internal Server Error)
      TypeError: Failed to fetch dynamically imported module: http://localhost:9463/test.js?wtr-session-id=c1055809-8910-44cb-a5d5-ba97ee8a29b9

 ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information.

Chrome: |██████████████████████████████| 1/1 test files | 0 passed, 0 failed

Error while running tests.
```

I've created a repro case here: https://github.com/arv/web-test-runner-br

**Comment by LarsDenBakker** [comment]
Thanks for posting a reproduction. We were serving compressed files if they exist - this doesn't work when there are plugins that need to transform the served files. Should be fixed with `@web/test-runner@0.7.23`
