### ISSUE TITLE
[test-runner] "Cannot read property 'decl' of undefined" in coverage

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#690]
Two files in the [PR for `vaadin-date-picker`](https://github.com/vaadin/vaadin-date-picker/pull/733) have this problem:

```
Cannot read property 'decl' of undefined
TypeError: Cannot read property 'decl' of undefined
    at /Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/annotator.js:89:31
    at Array.forEach ()
    at annotateFunctions (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/annotator.js:86:29)
    at annotateSourceCode (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/annotator.js:234:9)
    at HtmlReport.onDetail (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/html/index.js:409:33)
    at LcovReport. [as onDetail] (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-reports/lib/lcov/index.js:28:23)
    at Visitor.value (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-lib-report/lib/tree.js:38:38)
    at ReportNode.visit (/Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-lib-report/lib/tree.js:88:21)
    at /Users/sergey/vaadin/vaadin-date-picker-new/node_modules/istanbul-lib-report/lib/tree.js:92:19
    at Array.forEach ()
```

As you can see the numbers are there:

![Screenshot 2020-10-05 at 13 30 19](https://user-images.githubusercontent.com/10589913/95069169-fb2e8a80-070e-11eb-898d-68beb86a8c18.png)

But when opening the files, I get this:

![Screenshot 2020-10-05 at 13 30 26](https://user-images.githubusercontent.com/10589913/95069172-fc5fb780-070e-11eb-88f7-40d004b4aa56.png)

![Screenshot 2020-10-05 at 13 30 33](https://user-images.githubusercontent.com/10589913/95069180-fd90e480-070e-11eb-976d-81bdce50574e.png)

**Comment by web-padawan** [comment]
Duplicate of #689 (got an error when submitting the previous issue as the browser tab was open for a while).
