### ISSUE TITLE
[test-runner] Unable to run tests with 0.9.2

### ISSUE THREAD

**Issue by Niznikr** [modernweb-dev/web#740]
I tried upgrading from `0.9.0` to `0.9.2` and got the following error when running the tests locally. We use `test-runner-playwright` for running tests and esbuildPlugin from `@web/dev-server-esbuild` with `ts` set to true:
```
Error while running tests:
TypeError: Cannot read property 'on' of undefined
    at TestRunnerApiPlugin.serverStart (/Users/rniznik/Documents/pharos/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/server/plugins/testRunnerApiPlugin.js:57:20)
    at DevServer.start (/Users/rniznik/Documents/pharos/node_modules/@web/dev-server-core/dist/server/DevServer.js:38:86)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TestRunnerServer.start (/Users/rniznik/Documents/pharos/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/server/TestRunnerServer.js:49:9)
    at async TestRunner.start (/Users/rniznik/Documents/pharos/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:56:13)
    at async Object.startTestRunner (/Users/rniznik/Documents/pharos/node_modules/@web/test-runner-cli/dist/startTestRunner.js:31:5)
```

**Comment by LarsDenBakker** [comment]
Is your playwright version also up to date? This can create issues sometimes.

**Comment by Niznikr** [comment]
Yup set `@web/test-runner-playwright` to `0.6.4` and `@web/dev-server-esbuild` to `0.2.5`

**Comment by LarsDenBakker** [comment]
I tried in some different projects, and  there it's working fine.

Looking at the error there is a nested installation of test-runner-core, possible because of a lockfile. I just released a new version of test runner, CLI and core together. That should hopefully put those things back in sync if you update to 0.9.3. Otherwise you could try reinstalling without a lockfile.

**Comment by Niznikr** [comment]
@LarsDenBakker Will give that a try thanks!
