### ISSUE TITLE
[rollup-plugin-html] Looking for remote assets on local file system

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#797]
When processing this html:
```
<img src="https://img.shields.io/npm/v/@spectrum-web-components/accordion?style=for-the-badge" alt="See it on NPM!">
```
The plugin seems to mistake this for a local asset and throws on processing:
```
documentation: [!] Error: Could not find /Users/westbrook/Documents/web/repos/spectrum-web-components/projects/documentation/_site/components/accordion/api/https:/img.shields.io/npm/v/@spectrum-web-components/accordion?style=for-the-badge referenced from HTML file _site/components/accordion/api/index.html from element .
documentation: Error: Could not find /Users/westbrook/Documents/web/repos/spectrum-web-components/projects/documentation/_site/components/accordion/api/https:/img.shields.io/npm/v/@spectrum-web-components/accordion?style=for-the-badge referenced from HTML file _site/components/accordion/api/index.html from element .
documentation:     at Object.extractAssets (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/@web/rollup-plugin-html/src/input/extract/extractAssets.ts:28:15)
documentation:     at Object.extractModulesAndAssets (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/@web/rollup-plugin-html/src/input/extract/extractModulesAndAssets.ts:21:7)
documentation:     at createInputData (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/@web/rollup-plugin-html/src/input/getInputData.ts:39:18)
documentation:     at Object.getInputData (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/@web/rollup-plugin-html/src/input/getInputData.ts:75:22)
documentation:     at Object.options (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/@web/rollup-plugin-html/src/rollupPluginHTML.ts:42:16)
documentation:     at /Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/rollup/dist/shared/rollup.js:19408:36
documentation:     at getInputOptions (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/rollup/dist/shared/rollup.js:19401:61)
documentation:     at Object.rollupInternal (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/rollup/dist/shared/rollup.js:19360:72)
documentation:     at Task.run (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/rollup/dist/shared/watch.js:715:28)
documentation:     at Watcher.run (/Users/westbrook/Documents/web/repos/spectrum-web-components/node_modules/rollup/dist/shared/watch.js:640:17)
```
Seems like maybe we should gate assets by the presence of a protocol at the front? Or maybe, preload that asset from remote and build it into my build 🤔 💡 💭 🤯 ?

**Comment by Westbrook** [comment]
Not sure if we should just return `false` if the asset has protocol or isn't otherwise provably local? 

https://github.com/modernweb-dev/web/blob/3776aff3ee975507007052b540566ecb8b307127/packages/rollup-plugin-html/src/assets/utils.ts#L9-L18

**Comment by LarsDenBakker** [comment]
I think the common goal for putting a full URL is to load it from a remote location, so filtering those out would be best.

Duplicate of: https://github.com/modernweb-dev/web/issues/782

**Comment by Westbrook** [comment]
yep, dupe.
