### ISSUE TITLE
[test-runner-saucelabs] Implement heartbeat to prevent timeout in 90 seconds

### ISSUE THREAD

**Issue by web-padawan** [modernweb-dev/web#945]
I have more than 900 tests in `vaadin-grid` repository and they fail in Safari in SauceLabs most of time.

When I tried to debug the tunnel, I got the following error in SauceLabs UI:

```There is a problem with your test.
Test did not see a new command for 90 seconds. Timing out.
```

And in the WTR output the following error is shown:

```
test/scroll-to-index.test.js:
 :x: Browser tests did not start after 120000ms You can increase this timeout with the testsStartTimeout option. Check the browser logs or open the browser in debug mode for more information. 
 :x: UnsupportedOperationError: executeScript: ERROR The test with session id ad4efc3223fa406e88423a1a876ecd0e has already finished, and can't receive further commands. 
      You can learn more at https://app.saucelabs.com/tests/ad4efc3223fa406e88423a1a876ecd0e
      For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
      at parseHttpResponse (/home/runner/work/***/***/node_modules/selenium-webdriver/lib/http.js:580:11)
      at Executor.execute (/home/runner/work/***/***/node_modules/selenium-webdriver/lib/http.js:491:26)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async WebDriver.execute (/home/runner/work/***/***/node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at async IFrameManager.stopSession (/home/runner/work/***/***/node_modules/@web/test-runner-selenium/dist/IFrameManager.js:101:29)
```

The Karma launcher has heartbeat logic: https://github.com/karma-runner/karma-sauce-launcher/pull/223

I'm not sure but most likely adding heartbeat would help to solve this problem.

**Comment by LarsDenBakker** [comment]
Giving the error message you're seeing in sauce, this seems like a possible fix to this issue
