### ISSUE TITLE
[test-runner-*] Investigate correct browser launch args for CI

### ISSUE THREAD

**Issue by RoXuS** [modernweb-dev/web#97]
We run tests inside gitlab-runner (docker) and we have this error:

```
[0615/200021.679091:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/builds/jrousseau/dt-organization/node_modules/puppeteer-core/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/builds/jrousseau/dt-organization/node_modules/puppeteer-core/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

TypeError: Cannot read property 'isConnected' of undefined
    at Object.stop (/builds/jrousseau/dt-organization/node_modules/@web/test-runner-chrome/dist/chromeLauncher.js:26:25)
    at TestRunner.stop (/builds/jrousseau/dt-organization/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:103:21)
    at TestRunner.quit (/builds/jrousseau/dt-organization/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:128:20)
    at TestRunner.start (/builds/jrousseau/dt-organization/node_modules/@web/test-runner-core/dist/runner/TestRunner.js:71:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.startTestRunner (/builds/jrousseau/dt-organization/node_modules/@web/test-runner-cli/dist/startTestRunner.js:106:5)
```

Any way to run test as root?

**Comment by LarsDenBakker** [comment]
Do you have Chrome installed in the CI? You could try running the tests with the `--puppeteer` flag, it will add a postinstall download of Chromium and might be safer to use within CI. 

I need to read up a bit more on these flags, but you could add the flags yourself in a config. I just added some docs for this: https://github.com/modernweb-dev/web/tree/master/packages/test-runner#customizing-browser-launch-options

**Comment by LarsDenBakker** [comment]
Updated the issue title for investigation

**Comment by LarsDenBakker** [comment]
Note you need to use v0.5.7

**Comment by RoXuS** [comment]
Work as expected, thx!
