### ISSUE TITLE
Uncomplete docs: HTML Tests

### ISSUE THREAD

**Issue by Krutsch** [modernweb-dev/web#981]
The documentations offer a [HTML file](https://modern-web.dev/docs/test-runner/writing-tests/html-tests/) that should work when running `wtr src/**/*.test.html --node-resolve`.

Instead, there will be an error:
```
src\compA\compA.test.html:

 ❌ HTML tests > works
      at: compA.test.html:148:13
      ReferenceError: expect is not defined
        at n.<anonymous> (compA.test.html:148:13)
        at node_modules\@web\test-runner-mocha\dist\standalone.js:1:224799
        at Hg.pd.run (node_modules\@web\test-runner-mocha\dist\standalone.js:1:225094)
        at Hd.runTest (node_modules\@web\test-runner-mocha\dist\standalone.js:1:238397)
        at node_modules\@web\test-runner-mocha\dist\standalone.js:1:239333
        at i (node_modules\@web\test-runner-mocha\dist\standalone.js:1:237782)
        at node_modules\@web\test-runner-mocha\dist\standalone.js:1:237852
        at i (node_modules\@web\test-runner-mocha\dist\standalone.js:1:236639)
        at node_modules\@web\test-runner-mocha\dist\standalone.js:1:237667
        at hm (node_modules\@web\test-runner-mocha\dist\standalone.js:1:285973)

Chrome: |██████████████████████████████| 1/1 test files | 0 passed, 1 failed

Finished running tests in 0.4s with 1 failed tests.
```

Could you update the docs to fix `expect is not defined`?

**EDIT:**
I could also create a PR to add 
`import { expect } from "https://unpkg.com/@esm-bundle/chai/esm/chai.js?module";`

**Comment by LarsDenBakker** [comment]
A PR would be great :) I think we should show:

```js
import { expect } from "@esm-bundle/chai";
```

**Comment by Krutsch** [comment]
[Created a PR.](https://github.com/modernweb-dev/web/pull/982)
