### ISSUE TITLE
[test-runner]: TypeError: Cannot read property 'replace' of undefined at V8ToIstanbul._resolveSource

### ISSUE THREAD

**Issue by bennypowers** [modernweb-dev/web#993]
PTAL at https://github.com/apollo-elements/apollo-elements/pull/95/checks?check_run_id=1437262112

```

packages/haunted/useMutation.test.ts:

 ❌ TypeError: Cannot read property 'replace' of undefined 
      at V8ToIstanbul._resolveSource (node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:86:29)
      at V8ToIstanbul.load (node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:57:26)
      at Object.v8ToIstanbul (node_modules/@web/test-runner-coverage-v8/dist/index.js:42:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (../../internal/process/task_queues.js:93:5)
      at async ChromeLauncherPage.stopSession (node_modules/@web/test-runner-chrome/dist/ChromeLauncherPage.js:28:30)
      at async ChromeLauncher.stopSession (node_modules/@web/test-runner-chrome/dist/ChromeLauncher.js:129:24)

```

I'm guessing the problem is somewhere in ApolloHook.ts, as I didn't get these errors prior to abstracting the base class out, and this file is common to all three failing test files.

https://github.com/apollo-elements/apollo-elements/blob/1bbd6f0f02007c3b7d8c9d845a8e5ae9fc4783f8/packages/haunted/ApolloHook.ts#L20-L119

**Comment by LarsDenBakker** [comment]
Do you have a more minimal reproduction?

**Comment by bennypowers** [comment]
My attempts to isolate a repro so far have been unsuccessful, however, I did manage to "solve" the problem by adding one line of code to `packages/interfaces/constructor.ts`. Before, this file contained only an `export declare class` statement and an `export type` statement. esbuild would have stripped those out, ostensibly. I added this line:

```ts
null;
```

Ostensibly, this gave the file enough runtime significance for it to sluice through the tooling unscathed. 

`constructor.ts` is exported from `packages/interfaces/index.ts`, and my code imports it from there.

https://github.com/apollo-elements/apollo-elements/blob/1bbd6f0f02007c3b7d8c9d845a8e5ae9fc4783f8/packages/haunted/ApolloHook.ts#L3

An important note: `packages/interfaces/index.ts` also exports from `packages/interfaces/apollo-*.ts`. prior to this PR, those files all also had no runtime significance, like `constructor.ts` without the `null;` expression. I noticed this behaviour after adding some runtime exports to `packages/interfaces/apollo-*.ts`, so It's possible that the root cause is

> When a file exports both types and runtime names from one file that has types and runtime code, while also exporting only types from a second file, that second file having only types

I'll see about putting such a repro together
